# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development
    command: ["flask", "run"]
